{
    "name": "Sch_management",
    "author": "Savan",
    "summary":"This is a school management system",
    "license": "LGPL-3",
    "depends":["mail","sale","base","account"],
    'data':[
        'security/res.groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'views/student_detail.xml',
        'views/parent.xml',
        'wizard/student_wiz.xml',
        'wizard/teacher_salary.xml',
        'views/standard.xml',
        'views/subject.xml',
        'views/teacher.xml',
        'views/library.xml',
        'views/book.xml',
        'views/exam.xml',
        'views/marksheet.xml',
        'views/hobby.xml',
        'views/department.xml',
        'views/property.xml',
        'data/seq_student.xml',
        'report/student_qweb.xml',
        'report/student_info_report.xml',
        'views/sale_order.xml',
        'views/stationery.xml',
        'views/invoice.xml',
        'views/product.xml',
        'wizard/student_excel.xml',
        'data/demo.xml',
        'data/student_email.xml',
        'views/menu.xml',   
        

    ]
    
}