from . import library
from . import parent 
from . import standard 
from . import subject 
from . import teacher
from . import book
from . import exam
from . import marksheet
from . import student_detail
from . import hobby
from . import department
from . import property
from . import sale_oder
from . import stationery
from . import invoice
from . import product